"""describe your changes here

Revision ID: 120fc93bba2c
Revises: 339e52587ba3
Create Date: 2026-05-28 14:12:54.689537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '120fc93bba2c'
down_revision: Union[str, Sequence[str], None] = '339e52587ba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'asset_allocations', 'staff', ['staff_id'], ['auth_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'asset_allocations', type_='foreignkey')
    # ### end Alembic commands ###
