"""Create table directories and departments

Revision ID: 514660cac8b2
Revises: 
Create Date: 2026-05-23 15:05:23.066235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '514660cac8b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    directorates_table = op.create_table('directorates',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directorates_name'), 'directorates', ['name'], unique=True)

    op.bulk_insert(directorates_table, [
        {"id": 1, "name": "Directorate of Budget, Fiscal and Economic Affairs"},
        {"id": 2, "name": "Directorate of Public Debt Management"},
        {"id": 3, "name": "Directorate of Accounting Services & Quality Assurance"},
        {"id": 4, "name": "Directorate of Public Investment & Portfolio Management"},
        {"id": 5, "name": "Public Private Partnerships (PPP) Directorate"},
        {"id": 6, "name": "Directorate of Administrative and Support Services"},
    ])

    departments_table = op.create_table('departments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('directorate_id', sa.Integer(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(['directorate_id'], ['directorates.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)

    op.bulk_insert(departments_table, [
        {"id": 1, "name": "Macro and Fiscal Affairs Department", "directorate_id": 1},
        {"id": 2, "name": "Budget Department", "directorate_id": 1},
        {"id": 3, "name": "Financial and Sectoral Affairs Department", "directorate_id": 1},
        {"id": 4, "name": "Inter-Governmental Fiscal Relations Department", "directorate_id": 1},
        {"id": 5, "name": "Public Procurement Department", "directorate_id": 1},
        {"id": 6, "name": "Resource Mobilization Department", "directorate_id": 2},
        {"id": 7, "name": "Debt Policy, Strategy and Risk Management Department", "directorate_id": 2},
        {"id": 8, "name": "Debt Recording and Settlement Department", "directorate_id": 2},
        {"id": 9, "name": "Government Accounting Services Department", "directorate_id": 3},
        {"id": 10, "name": "Internal Audit Department", "directorate_id": 3},
        {"id": 11, "name": "Financial Management Information Services (IFMIS) Department", "directorate_id": 3},
        {"id": 12, "name": "National Sub-County Treasuries Department", "directorate_id": 3},
        {"id": 13, "name": "Government Digital Payment Unit", "directorate_id": 3},
        {"id": 14, "name": "Government Investment and Public Enterprises Department", "directorate_id": 4},
        {"id": 15, "name": "Public Investment Management (PIM) Unit", "directorate_id": 4},
        {"id": 16, "name": "Pensions Department", "directorate_id": 4},
        {"id": 17, "name": "National Assets and Liabilities Management Department", "directorate_id": 4},
        {"id": 18, "name": "Human Resource Management & Development Department", "directorate_id": 6},
        {"id": 19, "name": "Legal Department", "directorate_id": 6},
        {"id": 20, "name": "Supply Chain Management Department", "directorate_id": 6},
        {"id": 21, "name": "ICT Department", "directorate_id": 6},
        {"id": 22, "name": "Central Planning Department", "directorate_id": 6},
        {"id": 23, "name": "Public Communications Department", "directorate_id": 6},
    ])

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_directorates_name'), table_name='directorates')
    op.drop_table('directorates')
    # ### end Alembic commands ###
