"""add fk to ict_personnel staff_id

Revision ID: 54fd007a10c1
Revises: bfba477f2e84
Create Date: 2026-05-28 11:32:39.404729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54fd007a10c1'
down_revision: Union[str, Sequence[str], None] = 'bfba477f2e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'ict_personnel', 'staff', ['staff_id'], ['auth_user_id'])
    op.drop_constraint(op.f('staff_auth_user_id_fkey'), 'staff', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('staff_auth_user_id_fkey'), 'staff', 'ict_personnel', ['auth_user_id'], ['staff_id'])
    op.drop_constraint(None, 'ict_personnel', type_='foreignkey')
    # ### end Alembic commands ###
