"""Create staff table

Revision ID: 5c6b28de7609
Revises: 514660cac8b2
Create Date: 2026-05-26 11:44:22.042967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5c6b28de7609'
down_revision: Union[str, Sequence[str], None] = '514660cac8b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('auth_user_id', sa.UUID(), nullable=False),
    sa.Column('personal_no', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('directorate_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('office_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('office_location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'staff', 'technician', name='userrole'), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('is_activated', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('banned_until', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['directorate_id'], ['directorates.id'], ),
    sa.PrimaryKeyConstraint('auth_user_id')
    )
    op.create_index(op.f('ix_staff_personal_no'), 'staff', ['personal_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_personal_no'), table_name='staff')
    op.drop_table('staff')
    # ### end Alembic commands ###
