"""add all models

Revision ID: bfba477f2e84
Revises: b17366860df9
Create Date: 2026-05-28 11:09:54.145822

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bfba477f2e84'
down_revision: Union[str, Sequence[str], None] = 'b17366860df9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ict_personnel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('specialization', sa.Enum('hardware', 'networking', 'software_and_systems', 'security', name='specialization'), nullable=False),
    sa.Column('availability', sa.Enum('available', 'busy', 'off_duty', 'on_leave', name='availability'), nullable=False),
    sa.Column('phone_extension', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ict_personnel')
    # ### end Alembic commands ###
