"""create ticket table

Revision ID: d2100fae1c2
Revises: 54fd007a10c1
Create Date: 2026-05-28 14:24:12.194052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd2100fae1c2'
down_revision: Union[str, Sequence[str], None] = '54fd007a10c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sa.Enum('hardware', 'software', 'network', 'access_permissions', 'security_incidents', 'other', name='ticketcategory'), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', name='ticketstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['ict_personnel.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.auth_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Tickets_title'), 'Tickets', ['title'], unique=False)
    op.drop_table('asset_allocations')
    op.drop_index(op.f('ix_assets_asset_tag'), table_name='assets')
    op.drop_index(op.f('ix_assets_serial_number'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('asset_tag', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('serial_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('device_type', postgresql.ENUM('laptop', 'desktop', 'monitor', 'printer', 'other', name='devicetype'), autoincrement=False, nullable=False),
    sa.Column('brand', postgresql.ENUM('dell', 'hp', 'lenovo', 'apple', 'asus', 'acer', 'huawei', 'other', name='brand'), autoincrement=False, nullable=False),
    sa.Column('condition', postgresql.ENUM('good', 'fair', 'poor', 'decommissioned', name='assetcondition'), autoincrement=False, nullable=False),
    sa.Column('purchase_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('warranty_expiry_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('assets_pkey'))
    )
    op.create_index(op.f('ix_assets_serial_number'), 'assets', ['serial_number'], unique=True)
    op.create_index(op.f('ix_assets_asset_tag'), 'assets', ['asset_tag'], unique=True)
    op.create_table('asset_allocations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('staff_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('allocation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('return_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('asset_allocations_asset_id_fkey')),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.auth_user_id'], name=op.f('asset_allocations_staff_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('asset_allocations_pkey'))
    )
    op.drop_index(op.f('ix_Tickets_title'), table_name='Tickets')
    op.drop_table('Tickets')
    # ### end Alembic commands ###
